#####################
# ~~ Domain name ~~ #
cluster_name: example.ctgkube.com

##########################
# ~~ Kops state store ~~ #
bucket_name: example-store

###############################################
# ~~ SSH public key to acces Kubernetes API ~~#
#ssh_pub_key: ~/.ssh/id_rsa.pub
ssh_pub_key: ~/.ssh/ctgkube.pub

########################################
# ~~ AWS environment for kubernetes ~~ #

# Match with your AWS profile in case of multi-account environment
aws_profile: default
aws_region: us-east-1

# Be careful, master_zones must match maser_node_count
# Example: can't have 1 master in 2 AWS availability zones
master_zones: us-east-1a
aws_zones: us-east-1a,us-east-1b,us-east-1c

# EC2 host sizing
# (Ubuntu 20.04 LTS)
base_image: ami-019212a8baeffb0fa

# Kubernetes master nodes
master_instance_type: t3.medium
master_node_count: 1

# Kubernetes worker nodes
worker_instance_type: t3.medium
worker_node_count: 3

############################################
# ~~ Let's encrypt domain's email owner ~~ #
email_owner: chaance.graves@ctginnovations.io

#########################
# ~~ Wordpress block ~~ #

# Use maintenance-svc to enable maintenance mode
# Default to varnish service varnish-svc (uncomment to activate)
# wordpress_service: maintenance-svc

# (probably should move this block to ansible role deploy_wordpress)
#wordpress_host: wordpress
#wordpress_bucket_name: ctgadget-wordpress-unique-bucket
