
helm_version: "v3.6.3"
helm_download_path: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
helm_darwin_download_path: "https://get.helm.sh/helm-{{ helm_version }}-darwin-amd64.tar.gz"
helm_official_repo: "https://charts.helm.sh/stable"
